# Generated by Django 5.2.2 on 2025-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_created=True, verbose_name='Data Registro')),
                ('ponto', models.CharField(max_length=5, verbose_name='Ponto')),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=11, verbose_name='Status')),
                ('uptime', models.CharField(max_length=31, verbose_name='Uptime')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
                'ordering': ['data_registro'],
            },
        ),
    ]
