# Generated by Django 5.2.2 on 2025-06-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processadores', '0004_delete_acompanhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(verbose_name='Data Inicial')),
                ('data_final', models.DateTimeField(verbose_name='Data Final')),
                ('problema_apresentado', models.TextField(verbose_name='Problema Apresentado')),
                ('acao_tomada', models.TextField(verbose_name='Ação Tomada')),
                ('status_sla', models.CharField(choices=[('dentro', 'DENTRO'), ('fora', 'FORA')], default='fora', max_length=10, verbose_name='Status')),
                ('duracao', models.DurationField(blank=True, editable=False, help_text='Duração total da ocorrência (calculado automaticamente)', null=True)),
                ('id_processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='processadores.processador')),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['-data_inicial'],
            },
        ),
    ]
