# Generated by Django 5.2.2 on 2025-06-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamento',
            options={'ordering': ['data_inicial'], 'verbose_name': 'Acompanhamento', 'verbose_name_plural': 'Acompanhamentos'},
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='acao_tomada',
            field=models.TextField(help_text='Ação realizada para retorno do equipamento', verbose_name='Ação Tomada'),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='data_final',
            field=models.DateTimeField(help_text='Data final da ocorrência', verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='data_inicial',
            field=models.DateTimeField(help_text='Data inicial da ocorrência', verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='problema_apresentado',
            field=models.TextField(help_text='Problema apresentado pelo equipamento', verbose_name='Problema Apresentado'),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='status_sla',
            field=models.CharField(choices=[('dentro', 'DENTRO DO PRAZO'), ('fora', 'FORA DO PRAZO')], default='fora', help_text='Essa ocorrência durou mais que 1 dia ? se sim, fora do prazo caso contrário dentro do prazo.', max_length=10, verbose_name='Status do SLA'),
        ),
    ]
