# Generated by Django 5.2.2 on 2025-07-28 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0002_alter_acompanhamento_options_and_more'),
        ('processadores', '0004_delete_acompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='id_processador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='processadores.processador', verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='status_sla',
            field=models.CharField(choices=[('dentro', 'DENTRO DO PRAZO'), ('fora', 'FORA DO PRAZO')], default='fora', help_text='Essa ocorrência durou mais que 1 dia ? se sim, fora do prazo, caso contrário, dentro do prazo.', max_length=10, verbose_name='Status do SLA'),
        ),
    ]
