# Generated by Django 5.2.2 on 2025-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto', models.CharField(max_length=6)),
                ('regiao', models.CharField(max_length=50)),
                ('nome_ponto', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('nome_camera', models.CharField(max_length=150, unique=True)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('porta', models.CharField(max_length=6)),
                ('modelo', models.CharField(blank=True, max_length=150, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('atualizado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cameras',
                'ordering': ['ponto'],
                'managed': False,
            },
        ),
    ]
