# Generated by Django 5.2.2 on 2025-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=10, verbose_name='Nome')),
                ('serie', models.CharField(max_length=10, verbose_name='Serie')),
                ('numero_processador', models.CharField(max_length=10, verbose_name='Numero Processador')),
                ('faixa', models.IntegerField()),
                ('contrato', models.CharField(max_length=250, verbose_name='Contrato')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereco')),
                ('latitude', models.CharField(max_length=10, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=10, verbose_name='Longitude')),
                ('velocidade', models.CharField(max_length=3, verbose_name='Velocidade')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('regional', models.CharField(max_length=50, verbose_name='Regional')),
                ('fabricante', models.CharField(max_length=20, verbose_name='Fabricante')),
                ('cliente', models.CharField(max_length=250, verbose_name='Cliente')),
                ('centro_custo', models.CharField(max_length=100, verbose_name='Centro custo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Processador',
                'verbose_name_plural': 'Processadores',
                'ordering': ['-identificacao'],
            },
        ),
    ]
