# Generated by Django 5.2.2 on 2025-06-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processadores', '0003_acompanhamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acompanhamento',
        ),
    ]
